#### Notation/Settings/Acronyms

Common settings

| symbol | setting |
|---|---|
| $n$ | a positive integer |
| $A$ | nonsingular $n$-by-$n$ matrix |
| $b$ | (column) vector of length $n$ |
| $x$ | (column) vector of length $n$ |

Acronyms

|Abbreviation| meaning|
|---|---|
| SPD | Symmetric positive definite |




**Problem of interest**

Given $A$ and $b$, find $x$ such that

$$ Ax = b. $$




#### Methods

- Methods for general matrices
   1. Direct methods
      - plain Gaussian elimination
      - Gaussian elimination using $PA = LU$ decomposition.
        - Preliminary: $A=LU$ decomposition
   2. Iterative methods
      - Jacobi iteration
      - Gauss-Seidel iteration
- Methods for SPD matrices
   1. Direct methods
      - Cholesky factorization
   2. Iterative methods
      - Conjugate gradient method
- Framework for improvements
   1. Preconditioning


#### Gaussian elimination


##### Augmented matrix

Compact rearrangement of a system of linear equations in matrix form

$$
\begin{aligned}
x+2 y-z & =3 \\
2 x+y-2 z & =3 \\
-3 x+y+z & =-6 
\end{aligned}
\leftrightarrow
\left[\begin{array}{rrr:r}
1 & 2 & -1 & 3 \\
2 & 1 & -2 & 3 \\
-3 & 1 & 1 & -6
\end{array}\right]
$$

##### Elementary row operations

1. Swap one equation (or a row) for another (row): $R_i \leftrightarrow R_j$.
2. Add or subtract a multiple of one equation (or a row) from another (row): $R_i \gets R_i + c R_j$.
3. Multiply an equation (or a row) by a nonzero constant: $R_i \gets c R_i$.


**Example**

Solve the following system of linear equations using the augmented matrix and elementary row operations: 

$$
\begin{aligned}
x+2 y-z & =3 \\
2 x+y-2 z & =3 \\
-3 x+y+z & =-6 .
\end{aligned}
$$

**Remark** (back substitution)

- While there can be many creative ways to find the solution, we will following one single way: we are *developing a systematic method*.
- Let us call, in this class, the first step *elimination*.
- The second step (finding unknowns one by one) is called *back substitution* or *back solving*.

##### Complexity of Gaussian elimination

| Step | Complexity (precise) | Complexity (order) | 
|------|------------|-----|
| eliminations | $$ \frac 2 3 n^3 + \frac 1 2 n^2 - \frac 7 6 n $$ | $$=\mathcal{O}(n^3) $$ | 
| back substitutions | $$ n^2 $$ |  $$= \mathcal{O}(n^2) $$ |

[Derivation of complexity of eliminations 1](../images/der_ComplexityGaussianEliminations1_lp2000.png)

[Derivation of complexity of eliminations 2](../images/der_ComplexityGaussianEliminations2_lp2000.png)

[Derivation of complexity of back substitions](../images/der_ComplexityBackSubstitutions_lp2000.png)

___

**Lemma** (Inverse of row elimination)

Let $A$ be an $n$-by-$n$ matrix whose diagonal elements are all 1, and only one column has nonzero elements below diagonal. Then, $A^{-1}$ is of the same form as $A$ except the signs of elements below diagonal being flipped.

In [17]:
"""This script verifies the inversion of a triangular matrix.

1. If only one column has nonzero element below the diagonal,
    then the matrix inversion is mechanical.
2. If more columns has nonzero elements below the diagonal,
    then inversion is not that simple. 
"""

import numpy as np

A = np.eye(3)
A[1, 0] = 2
A[2, 0] = -5
# A[2, 1] = 3 # uncomment this line to see case 2

B = A.copy()
low_diag_ind = np.tril_indices_from(B, -1)
B[low_diag_ind] = - A[low_diag_ind]

print("A: \n", A)
print("\nB: \n", B)
print("\nA*B: \n", A@B)
print("\nA^-1:\n", np.linalg.inv(A))


A: 
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-5.  0.  1.]]

B: 
 [[ 1.  0.  0.]
 [-2.  1.  0.]
 [ 5. -0.  1.]]

A*B: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

A^-1:
 [[ 1. -0. -0.]
 [-2.  1.  0.]
 [ 5.  0.  1.]]


___

##### Application of LU decomposition

- Solving systems of linear equations
- Determinant
- Inverting matrices

Reference: [Wikipedia](https://en.wikipedia.org/wiki/LU_decomposition#Applications)