## Trigonometric interpolation

**Notation**

| symbol | meaning |
|---|---|
| $\bar u$ | complex conjugate of $u$ (element-wise complex conjugate for vector or matrix) |
| $i$ | $=\sqrt{-1}$ imaginary unit |
| $v^H$, $A^H$ | $\overline{v}^T$, $\overline{A}^T$, where $v$ and $A$ are complex vector and matrix respectively (called *conjugate transpose*) |
| $(u, v)$ | $v^H u = \sum_{j=1}^n u_j \overline{v_j}$, where $u,v\in C^n$ (Complex dot-product) |
| $\lVert v \rVert$ | $\sqrt{(v, v)}$, where $v\in C^n$ (2-norm of complex vector) |
<!-- | $\mathfrak{i}$ | $=\sqrt{-1}$ imaginary unit (watch the font! $i$ vs $\mathfrak{i}=\sqrt{-1}$) | -->


### Facts on complex numbers

**Defintion** 

For $z=a+b i\in C$,

- $\bar z = a - b i$ (complex conjugate)
- $\mathrm{Re}(z):=a$ (real part) 
- $\mathrm{Im}(z):=b$ (imaginary part).
- $|z|:=\sqrt{z\bar z}=\sqrt{a^2 + b^2}$ (modulus, maginitude)
- $e^{i \theta} := \cos \theta+i \sin \theta$ (Euler formula)

**Facts**

1. For $z=a+b i\in C$, it is the case $z=r e^{i \theta}$, where $r = | z |$ and $\theta\in R$ is such that $\cos(\theta)=a$ and $\sin(\theta)=b$.
2. All exponent rules generalize to complex exponent in the Euler formula settings. That is, for $z,w\in C$, we have
   1. $e^z e^w = e^{z+w}$
   2. $e^z / e^w = e^{z-w}$
   3. $(e^z)^w = e^{zw}$
3. If $z\in C$ is on the unit circle, i.e. $|z|=1$, then $z^{-1}=\overline{z}$. In particular, $e^{-\theta i}=\overline{e^{\theta i}}$

![polar representation of complex number](https://www.researchgate.net/profile/Ovidiu-Bagdasar/publication/299680029/figure/fig4/AS:647955837108235@1531496118970/Algebraic-and-polar-representation-of-a-complex-number.png)

Figure: Ovidiu Bagdasar - ResearchGate (polar representation of complex number)

**Definition** (Root of unity)

Let $n$ be a positive integer. A complex number $\omega$ satisfying $\omega^n = 1$ is called a *root of unity*. If, in addition, $\omega^k\neq 1$ for $1 \le k < n$, then it is called *primitive root of unity*.

### Discrete Fourier Transform (DFT)

**Theorem** (Orthogonality of primitive roots of unity). 

Let $\omega$ be a primitive $n$-th root of unity and $k$ be an integer.
Then
$$
\sum_{j=0}^{n-1} \omega^{j k}=\left\{\begin{array}{ll}
n & \text { if } k / n \text { is an integer } \\
0 & \text { otherwise }
\end{array} .\right.
$$

In particular, $\omega=e^{\pm 2\pi \mathfrak{i}/n}$ satisfies this.

Proof: HW problem

This theorem reads:

$$
\begin{aligned}
1+\omega+\omega^2+\omega^3+\cdots+\omega^{n-1}&=0, \\
1+\omega^2+\omega^4+\omega^6+\cdots+\omega^{2(n-1)} & =0, \\
1+\omega^3+\omega^6+\omega^9+\cdots+\omega^{3(n-1)} & =0, \\
& \vdots \\
1+\omega^{n-1}+\omega^{(n-1) 2}+\omega^{(n-1) 3}+\cdots+\omega^{(n-1)(n-1)} & =0, \\
1+\omega^n+\omega^{2 n}+\omega^{3 n}+\cdots+\omega^{n(n-1)} &= n.
\end{aligned}
$$

For $k > n$, 

$$
\begin{aligned}
1+\omega^{n+1}+\omega^{(n+1)2}+\omega^{(n+1)3}+\cdots+\omega^{(n+1)(n-1)}&=0, \\
1+\omega^{n+2}+\omega^{(n+2)2}+\omega^{(n+2)2}+\cdots+\omega^{(n+2)(n-1)}&=0, \\
& \vdots \\
1+\omega^{2n-1}+\omega^{(2n-1) 2}+\omega^{(2n-1) 3}+\cdots+\omega^{(2n-1)(n-1)} & =0, \\
1+\omega^{2n}+\omega^{4 n}+\omega^{6 n}+\cdots+\omega^{2n(n-1)} &= n.
\end{aligned}
$$

For $k < 0$,

$$
\begin{aligned}
1+\omega^{-n+1}+\omega^{(-n+1)2}+\omega^{(-n+1)3}+\cdots+\omega^{(-n+1)(n-1)}&=0, \\
1+\omega^{-n+2}+\omega^{(-n+2)2}+\omega^{(-n+2)2}+\cdots+\omega^{(-n+2)(n-1)}&=0, \\
& \vdots \\
1+\omega^{-1}+\omega^{(-1) 2}+\omega^{(-1) 3}+\cdots+\omega^{(-1)(n-1)} & =0, \\
1+\omega^{-n}+\omega^{-2 n}+\omega^{-3 n}+\cdots+\omega^{-n(n-1)} &= n.
\end{aligned}
$$


**Definition** (Discrete Fourier Transform)

The Discrete Fourier Transform (DFT) of $x=\left[x_0, \ldots, x_{n-1}\right]^T$ is the $n$-dimensional vector $y=\left[y_0, \ldots, y_{n-1}\right]$, where $\omega=e^{-i 2 \pi / n}$ and
$$
y_k=\frac{1}{\sqrt{n}} \sum_{j=0}^{n-1} x_j \omega^{j k} .
$$

- Matrix form

$$
\left[\begin{array}{c}
y_0 \\
y_1 \\
y_2 \\
\vdots \\
y_{n-1}
\end{array}\right]=\left[\begin{array}{c}
a_0+i b_0 \\
a_1+i b_1 \\
a_2+i b_2 \\
\vdots \\
a_{n-1}+i b_{n-1}
\end{array}\right]=\frac{1}{\sqrt{n}}\left[\begin{array}{ccccc}
\omega^0 & \omega^0 & \omega^0 & \cdots & \omega^0 \\
\omega^0 & \omega^1 & \omega^2 & \cdots & \omega^{n-1} \\
\omega^0 & \omega^2 & \omega^4 & \cdots & \omega^{2(n-1)} \\
\omega^0 & \omega^3 & \omega^6 & \cdots & \omega^{3(n-1)} \\
\vdots & \vdots & \vdots & & \vdots \\
\omega^0 & \omega^{n-1} & \omega^{2(n-1)} & \cdots & \omega^{(n-1)^2}
\end{array}\right]\left[\begin{array}{c}
x_0 \\
x_1 \\
x_2 \\
\vdots \\
x_{n-1}
\end{array}\right] .
$$

- The $n \times n$ matrix above is called the Fourier matrix
$$
F_n=\frac{1}{\sqrt{n}}\left[\begin{array}{ccccc}
\omega^0 & \omega^0 & \omega^0 & \cdots & \omega^0 \\
\omega^0 & \omega^1 & \omega^2 & \cdots & \omega^{n-1} \\
\omega^0 & \omega^2 & \omega^4 & \cdots & \omega^{2(n-1)} \\
\omega^0 & \omega^3 & \omega^6 & \cdots & \omega^{3(n-1)} \\
\vdots & \vdots & \vdots & & \vdots \\
\omega^0 & \omega^{n-1} & \omega^{2(n-1)} & \cdots & \omega^{(n-1)^2}
\end{array}\right] .
$$


**Facts** (Fourier matrix)

- $y_k=a_k+i b_k$ is a complex number. 

- Fourier matrix is symmetric. 
- The first row of $n$-by-$n$ Fourier matrix adds up to $n$. Each of the other rows adds up to 0.
  - This is a consequence of the Orthogonalizty theorem on primitive roots of unity.
- $F_n^{-1}=\overline{F_n}$.
  - Proof: HW problem
$$
F_n^{-1}=\frac{1}{\sqrt{n}}\left[\begin{array}{ccccc}
\omega^0 & \omega^0 & \omega^0 & \cdots & \omega^0 \\
\omega^0 & \omega^{-1} & \omega^{-2} & \cdots & \omega^{-(n-1)} \\
\omega^0 & \omega^{-2} & \omega^{-4} & \cdots & \omega^{-2(n-1)} \\
\omega^0 & \omega^{-3} & \omega^{-6} & \cdots & \omega^{-3(n-1)} \\
\vdots & \vdots & \vdots & & \vdots \\
\omega^0 & \omega^{-(n-1)} & \omega^{-2(n-1)} & \cdots & \omega^{-(n-1)^2}
\end{array}\right],
$$

**Definition** (Inverse Discrete Fourier Transform (IDFT))

For $y\in C^n$, the map $y\mapsto F^{-1}_n y \in C^n$ is called Inverse Discrete Fourier Transform.

**Remark** (Intuition)

- Discrete Cosine Transform (DCT) bears the same idea as DFT. Since DFT involves complex numbers, and DCT doesn't, DCT can be visualized easily, and it is often used as a substitute visualization of DFT.
- DFT or DCT decompose a wave/signal (input of DFT or DCT; time domain) into frequencies (output of DFT or DCT).
- IDFT or IDCT reconstruct a signal from the frequency profile.

![Discrete Cosine Transform](https://pythonnumericalmethods.studentorg.berkeley.edu/_images/24.02.02-time_frequency.png)

Figure: [Kong, Siauw, Bayen](https://pythonnumericalmethods.studentorg.berkeley.edu/notebooks/chapter24.02-Discrete-Fourier-Transform.html) (Discrete Cosine Transform)

**Example** 

Find the DFT of $x=[1, 0, -1, 0]^T$ and $z=[1, 2, 3, 4]^T$.



In [13]:
import numpy as np

x = np.array([1., 0., -1., 0.])
z = np.array([1., 2., 3., 4.])

n = len(x)

w = np.exp(-2.*np.pi*1j/n)

kk = np.arange(n)
pow = (kk * kk.reshape(-1,1))
F = w**pow
y1 = (1./np.sqrt(n)) * (F@x)
y2 = (1./np.sqrt(n)) * (F@z)

with np.printoptions(precision=2, suppress=True):
    print(pow)
    print(F)
    print(y1)
    print(y2)


[[0 0 0 0]
 [0 1 2 3]
 [0 2 4 6]
 [0 3 6 9]]
[[ 1.+0.j  1.+0.j  1.+0.j  1.+0.j]
 [ 1.+0.j  0.-1.j -1.-0.j -0.+1.j]
 [ 1.+0.j -1.-0.j  1.+0.j -1.-0.j]
 [ 1.+0.j -0.+1.j -1.-0.j  0.-1.j]]
[0.+0.j 1.+0.j 0.-0.j 1.+0.j]
[ 5.+0.j -1.+1.j -1.-0.j -1.-1.j]


**Theorem** (DFT of real vector)

Let $\left\{y_k\right\}$ be the DFT of $\left\{x_j\right\}$, where the $x_j$ are real numbers. Then, 
- $y_0$ is real, and 
- $y_{n-k}=\bar{y}_k$ for $k=1, \ldots, n-1$.

###### proof

Proof. 

(First) 

This is clear: $y_0$ is the sum of the $x_j$ 's divided by $\sqrt{n}$

(Second) 

- Observation 1: $\omega^{n-k}=\overline{\omega^k}$ for $k=1,2,\cdots,n$.  
  - $\omega^{n-k}=e^{-i 2 \pi(n-k) / n}=e^{-i 2 \pi} e^{i 2 \pi k / n}=e^{i 2 \pi k / n}=\overline{e^{-i 2 \pi k / n}}=\omega^k$
- Observation 2: $\overline{x_j}=x_j$ for $j=1,2,\cdots,n$.
  - $x_j$'s are all real.

From the definition of Fourier transform, 
$$
\begin{aligned}
y_{n-k} & =\frac{1}{\sqrt{n}} \sum_{j=0}^{n-1} x_j\left(\omega^{n-k}\right)^j \\
& =\frac{1}{\sqrt{n}} \sum_{j=0}^{n-1} x_j \left(\overline{\omega^k}\right)^j \\
& =\frac{1}{\sqrt{n}} \sum_{j=0}^{n-1} \overline{x_j\left(\omega^k\right)^j}=\overline{y_k} .
\end{aligned}
$$

**Example**

Let $n$ be even and the $x_0, \ldots, x_{n-1}$ be real numbers. Then, the DFT of $x$ replaces them with exactly $n$ other real numbers $a_0, a_1, b_1, a_2, b_2, \ldots, a_{n / 2}$, the real and imaginary parts of the Fourier transform $y_0, \ldots, y_{n-1}$. For example, the $n=8$ DFT has the form
$$
F_8\left[\begin{array}{l}
x_0 \\
x_1 \\
x_2 \\
x_3 \\
x_4 \\
x_5 \\
x_6 \\
x_7
\end{array}\right]=\left[\begin{array}{l}
a_0 \\
a_1+i b_1 \\
a_2+i b_2 \\
a_3+i b_3 \\
a_4 \\
a_3-i b_3 \\
a_2-i b_2 \\
a_1-i b_1
\end{array}\right]=\left[\begin{array}{c}
y_0 \\
\vdots \\
y_{\frac{n}{2}-1} \\
y_{\frac{n}{2}} \\
\bar{y}_{\frac{n}{2}-1} \\
\vdots \\
\bar{y}_1
\end{array}\right] .
$$

**Remark** 

This property is exploited by software.

- `numpy.fft.rfft` stores only the essential part of the DFT.
  - This improves computation and memory.
  - But one needs to be a bit more careful because the shapes of the input and output are different.

### Fast Fourier Transform (FFT)